# Generated by Django 5.2.8 on 2025-11-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('proposal_file', models.FileField(upload_to='proposals/')),
                ('revised_file', models.FileField(blank=True, null=True, upload_to='revised_proposals/')),
                ('budget_file', models.FileField(blank=True, null=True, upload_to='budgets/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('current_step', models.IntegerField(choices=[(1, 'Format Checking'), (2, 'Plagiarism Checking'), (3, 'Evaluation'), (4, 'Seminar'), (5, 'Research Committee'), (6, 'Rector Approval')], default=1)),
                ('plagiarism_percentage', models.FloatField(blank=True, null=True)),
                ('evaluator_1_marks', models.FloatField(blank=True, null=True)),
                ('evaluator_2_marks', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
