# Generated by Django 5.2.8 on 2026-01-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_remove_proposal_evaluator_1_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='allocated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
