# Generated by Django 5.2.8 on 2026-01-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_proposal_allocated_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeereview',
            name='allocated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
